name: clang-tidy-post

on:
  workflow_run:
    # The name field of the lint action
    workflows: ["clang-tidy-review"]
    types: [completed]

permissions:
  pull-requests: write

jobs:

  post:
    runs-on: ubuntu-latest
    # We still want to run this check in case its required to pass even upon skip. 
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}

    steps:
      - uses: ZedThree/clang-tidy-review/post@v0.19.0
        # lgtm_comment_body, max_comments, and annotations need to be set on the posting workflow in a split setup
        with:
          # adjust options as necessary
          lgtm_comment_body: ''
          annotations: false
          max_comments: 10
