name: doxygen-build

on:
  pull_request:
  workflow_dispatch:

jobs:

  check-diff:
    runs-on: ubuntu-latest
    outputs: 
      handle: ${{ steps.check.outputs.run }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 2

      # The goal is to force this to pass if it does not need to run.
      - name: Check the diff
        id: check
        run: |
          echo "Here are the changed header files:"
          echo "$(git --no-pager diff --name-only HEAD HEAD~1 | grep -E '\.(h)$')"
          if git --no-pager diff --name-only HEAD HEAD~1 | grep -qE '\.(h)$'; then
            echo "run=true" >> $GITHUB_OUTPUT
            echo "Header files have changed, rebuilding Doxyfile..."
          else
            echo "run=false" >> $GITHUB_OUTPUT
            echo "Header files have NOT changed, skipping Doxyfile build..."
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-diff
    if: ${{ needs.check-diff.outputs.handle == 'true' }}

    steps:

    - name: Sanity Check
      run: |
        echo "${{ needs.check-diff.outputs.handle }}"

    - name: Checkout code
      uses: actions/checkout@v4
  
    - name: Install doxygen
      uses: ssciwr/doxygen-install@v1 
      with:
          version "1.9.1"

    - name: Install graphviz
      uses: ts-graphviz/setup-graphviz@v2

    - name: Build Doxyfile
      run: |
          doxygen Doxyfile
