name: sanitizer-build

on:
  pull_request:
  workflow_dispatch:

jobs:
  check-diff:
    runs-on: ubuntu-latest
    outputs: 
      handle: ${{ steps.check.outputs.run }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 2

      # The goal is to force this to pass if it does not need to run.
      - name: Check the diff
        id: check
        run: |
          echo "Here are the changed build/C files:"
          echo "$(git --no-pager diff --name-only HEAD HEAD~1 | grep -E '\.(c|h)$|\.cmake|CMakeLists|Config\.cmake\.in')"
          if git diff --name-only HEAD HEAD~1 | grep -qE '\.(c|h)$|\.cmake|CMakeLists|Config\.cmake\.in'; then
            echo "run=true" >> $GITHUB_OUTPUT
            echo "Implementation and/or build files have changed, rebuilding..."
          else
            echo "run=false" >> $GITHUB_OUTPUT
            echo "Implementation and/or build files have NOT changed, skipping build..."
          fi

  build:
    runs-on: ubuntu-latest
    needs: check-diff
    if: ${{ needs.check-diff.outputs.handle == 'true' }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - uses: lukka/get-cmake@latest 

    - name: Build Debug Sanitized Checks GCC
      run: |
        cmake --preset=gcc-dsan && cmake --build build -j$(nproc) --target ccc tests
    
    - name: Test Debug Sanitized
      run: |
        make dtest

    - name: Build Release Sanitized Checks GCC
      run: |
        make clean
        cmake --preset=gcc-rsan && cmake --build build -j$(nproc) --target ccc tests
        
    - name: Test Release Sanitized
      run: |
        make rtest
